[dotfiles]
"~/.config/mise/.miserc.toml" = { mode = "track", variants = [{ profile = "omarchy" }, { profile = "macos" }] }
"~/.config/mise/config.toml" = { mode = "track" }
"~/.config/mise/conf.d/dotfiles.toml" = { mode = "track" }
"~/.config/mise/conf.d/global.toml" = { mode = "track" }
"~/.config/helix/config.toml" = { mode = "track", variants = [{ profile = "omarchy" }, { profile = "macos" }] }

# Omarchy
"~/.config/hypr/autostart.lua" = { mode = "track", variants = [{ profile = "omarchy" }] }
"~/.config/hypr/bindings.lua" = { mode = "track", variants = [{ profile = "omarchy" }] }
"~/.config/hypr/hyprland.lua" = { mode = "track", variants = [{ profile = "omarchy" }] }
"~/.config/hypr/input.lua" = { mode = "track", variants = [{ profile = "omarchy" }] }
"~/.config/hypr/looknfeel.lua" = { mode = "track", variants = [{ profile = "omarchy" }] }
"~/.config/hypr/monitors.lua" = { mode = "track", variants = [{ profile = "omarchy" }] }
