theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
scrolloff = 5
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
# - = [":new", ":insert-output yazi", ":buffer-close!", ":redraw"]
