[tools]
gh = "latest"
lazydocker = "latest"
node = "latest"
pnpm = "latest"
usage = "latest"
opencode = "latest"
"github:lusingander/serie" = "latest"
"github:byron/dua-cli" = "latest"

[settings]
experimental = true
