gui:
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
  
  authorColors:
    '*': '#b4befe'

# customCommands:
#   - key: "<c-a>"
#     command: "env GITHUB_API_KEY='$(cocopilot)' git diff --cached | aichat --prompt 'Generate a clear and concise commit message. Follow the conventional commit message format.'"
#     context: "files"
#     loadingText: "Generating commit message..."
#     description: "Generating commit message with AI"
#     showOutput: true
#     outputTitle: "Commit Message (Copied)"
#     background: true
