theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
scrolloff = 5
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[keys.normal]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
A-J = ["extend_to_line_bounds", "yank", "paste_after"]
A-K = ["extend_to_line_bounds", "yank", "paste_before"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
- = [
  ':sh rm -f /tmp/unique-file',
  ':sh rm -f /tmp/unique-cwd-file',
  ":insert-output yazi --chooser-file=/tmp/unique-file --cwd-file=/tmp/unique-cwd-file",
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':cd %sh{cat /tmp/unique-cwd-file}',
  ':redraw',
]
