[tools]
agent-browser = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
codex = "latest"
dotnet = "latest"
fnox = "latest"
gh = "latest"
node = "26.9.0"
opencode = "latest"
pi = "latest"
pnpm = "latest"

[settings.upgrade]
auto_prune = false

[settings]
minimum_release_age_excludes = ["pi"]
